# Generated by Django 5.1 on 2024-09-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Land_plots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('recorded_area', models.CharField(max_length=255)),
                ('parcel_code', models.IntegerField(max_length=255)),
                ('crop_type', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'land_plots',
            },
        ),
    ]
